### PR TITLE
Tweaks JavaScript to render demo HTML

### PR DESCRIPTION
**Pull request by locks**
Preview of HTML output

Current output above.
I'm not sure how to highlight all the code blocks.

### CODE REVIEW

**Comment by bobthecow** [comment]
Use CodeMirror for the code input.

**Comment by locks** [comment]
@bobthecow can you send a PR against this?

**Comment by bobthecow** [comment]
@locks no time this weekend, unfortunately.

**Comment by raghunayyar** [comment]
@bobthecow can you send a PR on my repo? This is will solve the entire redesign problem. Here is a link of my PR here. You can check. :)
https://github.com/mustache/mustache.github.com/pull/72

**Comment by jgonggrijp** [comment]
Obsolete due to #156.

**Pull request closed without merging**
