### PR TITLE
Added PowerShell implementation (PSMustache)

### PR DESCRIPTION
**Pull request by splumhoff**
Added my PowerShell implementation PSMustache to the list of implementations

### CODE REVIEW

**Comment by jgonggrijp** [comment]
@splumhoff What is your reason for closing? I recently became a maintainer and I could merge your changes.

**Comment by splumhoff** [comment]
Thanks for asking. Reason is inactivity of the upstream repo and cleanup of my stale repos.
I didn't expected that the commit would finally be merged after 2,5 years. ;-)
Can you still merge the closed PR or do I need to recreate it?

**Comment by jgonggrijp** [comment]
I can still see the changes, so I should be able to get it in without your help. Thanks for your contribution!

**Comment by jgonggrijp** [comment]
@splumhoff success 👍

**Pull request closed without merging**
